### ISSUE TITLE
remove duplicate dependency

### ISSUE THREAD

**Issue by sushmitha007** [samareshmaiti/track-service-h2-database#5]
https://github.com/samareshmaiti/spring-boot-tasks/blob/track-service-additional-properties/pom.xml
   <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
            <version>2.1.6.RELEASE</version>
        </dependency>
        
        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-jpa</artifactId>
            <version>2.1.9.RELEASE</version>
        </dependency>

**Comment by samareshmaiti** [comment]
issue closed
