### ISSUE TITLE
remove unused dependency: 

### ISSUE THREAD

**Issue by sushmitha007** [samareshmaiti/track-service-h2-database#6]
https://github.com/samareshmaiti/spring-boot-tasks/blob/track-service-mongodb/pom.xml
spring-boot-tasks/pom.xml
<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            
        </dependency>
        
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
            <version>2.1.6.RELEASE</version>
        </dependency>

**Comment by samareshmaiti** [comment]
issue closed
